# Generated by Django 5.2.6 on 2025-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('manager', 'Manager')], default='player', max_length=16),
        ),
    ]
