# Generated by Django 5.2.7 on 2025-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
