# Generated by Django 5.2.6 on 2025-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
