# Generated by Django 5.2.6 on 2025-10-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_avatar_key_only'),
        ('accounts', '0004_user_coin_balance'),
    ]

    operations = [
    ]
