/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customRequest } from "../../custom-client";

/**
 * List the last 50 bookings of the logged-in user.
 Endpoint:
GET /api/my-booking/
 */
export const myBookingRetrieve = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/my-booking/`,
    method: "GET",
    signal,
  });
};

export const getMyBookingRetrieveQueryKey = () => {
  return [`/api/my-booking/`] as const;
};

export const getMyBookingRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof myBookingRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof myBookingRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMyBookingRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof myBookingRetrieve>>
  > = ({ signal }) => myBookingRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof myBookingRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MyBookingRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof myBookingRetrieve>>
>;
export type MyBookingRetrieveQueryError = unknown;

export function useMyBookingRetrieve<
  TData = Awaited<ReturnType<typeof myBookingRetrieve>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof myBookingRetrieve>>,
          TError,
          Awaited<ReturnType<typeof myBookingRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMyBookingRetrieve<
  TData = Awaited<ReturnType<typeof myBookingRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof myBookingRetrieve>>,
          TError,
          Awaited<ReturnType<typeof myBookingRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMyBookingRetrieve<
  TData = Awaited<ReturnType<typeof myBookingRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMyBookingRetrieve<
  TData = Awaited<ReturnType<typeof myBookingRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMyBookingRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
