/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customRequest } from "../../custom-client";

/**
 * Monthly slot overview for a given club.
GET /month-view/?club=1&month=2025-10
 */
export const monthViewRetrieve = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/month-view/`,
    method: "GET",
    signal,
  });
};

export const getMonthViewRetrieveQueryKey = () => {
  return [`/api/month-view/`] as const;
};

export const getMonthViewRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof monthViewRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof monthViewRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMonthViewRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof monthViewRetrieve>>
  > = ({ signal }) => monthViewRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof monthViewRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MonthViewRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof monthViewRetrieve>>
>;
export type MonthViewRetrieveQueryError = unknown;

export function useMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof monthViewRetrieve>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof monthViewRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monthViewRetrieve>>,
          TError,
          Awaited<ReturnType<typeof monthViewRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof monthViewRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof monthViewRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monthViewRetrieve>>,
          TError,
          Awaited<ReturnType<typeof monthViewRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof monthViewRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof monthViewRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof monthViewRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof monthViewRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMonthViewRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
