# Generated by Django 5.2.7 on 2025-10-31 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topuprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='transfer_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='amount_thb',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='slip_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='wallet/slips/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL),
        ),
    ]
