# Generated by Django 5.2.8 on 2025-11-09 18:31

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_topuprequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='slip_path',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=storages.backends.s3.S3Storage(), upload_to='wallet/slips/%Y/%m/%d/'),
        ),
    ]
