/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CourtlyTokenObtainPair,
  Register,
  TokenRefresh,
} from "../../schemas";

import { customRequest } from "../../custom-client";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

/**
 * POST /api/auth/login/ with {username,password} or {email,password}
Returns: {access, refresh, firstLogin, user}
 */
export const authAuthLoginCreate = (
  courtlyTokenObtainPair: CourtlyTokenObtainPair,
  signal?: AbortSignal,
) => {
  return customRequest<CourtlyTokenObtainPair>({
    url: `/api/auth/auth/login/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: courtlyTokenObtainPair,
    signal,
  });
};

export const getAuthAuthLoginCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthLoginCreate>>,
    TError,
    { data: CourtlyTokenObtainPair },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authAuthLoginCreate>>,
  TError,
  { data: CourtlyTokenObtainPair },
  TContext
> => {
  const mutationKey = ["authAuthLoginCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authAuthLoginCreate>>,
    { data: CourtlyTokenObtainPair }
  > = (props) => {
    const { data } = props ?? {};

    return authAuthLoginCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthAuthLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authAuthLoginCreate>>
>;
export type AuthAuthLoginCreateMutationBody = CourtlyTokenObtainPair;
export type AuthAuthLoginCreateMutationError = unknown;

export const useAuthAuthLoginCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authAuthLoginCreate>>,
      TError,
      { data: CourtlyTokenObtainPair },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authAuthLoginCreate>>,
  TError,
  { data: CourtlyTokenObtainPair },
  TContext
> => {
  const mutationOptions = getAuthAuthLoginCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * POST /api/auth/register/
Body accepts: username, email, password, confirm, firstname, lastname, accept
(serializer maps firstname/lastname -> first_name/last_name)
 */
export const authAuthRegisterCreate = (
  register: Register,
  signal?: AbortSignal,
) => {
  return customRequest<Register>({
    url: `/api/auth/auth/register/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: register,
    signal,
  });
};

export const getAuthAuthRegisterCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthRegisterCreate>>,
    TError,
    { data: Register },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authAuthRegisterCreate>>,
  TError,
  { data: Register },
  TContext
> => {
  const mutationKey = ["authAuthRegisterCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authAuthRegisterCreate>>,
    { data: Register }
  > = (props) => {
    const { data } = props ?? {};

    return authAuthRegisterCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthAuthRegisterCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authAuthRegisterCreate>>
>;
export type AuthAuthRegisterCreateMutationBody = Register;
export type AuthAuthRegisterCreateMutationError = unknown;

export const useAuthAuthRegisterCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authAuthRegisterCreate>>,
      TError,
      { data: Register },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authAuthRegisterCreate>>,
  TError,
  { data: Register },
  TContext
> => {
  const mutationOptions = getAuthAuthRegisterCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authAuthTokenRefreshCreate = (
  tokenRefresh: NonReadonly<TokenRefresh>,
  signal?: AbortSignal,
) => {
  return customRequest<TokenRefresh>({
    url: `/api/auth/auth/token/refresh/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tokenRefresh,
    signal,
  });
};

export const getAuthAuthTokenRefreshCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthTokenRefreshCreate>>,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authAuthTokenRefreshCreate>>,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationKey = ["authAuthTokenRefreshCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authAuthTokenRefreshCreate>>,
    { data: NonReadonly<TokenRefresh> }
  > = (props) => {
    const { data } = props ?? {};

    return authAuthTokenRefreshCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthAuthTokenRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authAuthTokenRefreshCreate>>
>;
export type AuthAuthTokenRefreshCreateMutationBody = NonReadonly<TokenRefresh>;
export type AuthAuthTokenRefreshCreateMutationError = unknown;

export const useAuthAuthTokenRefreshCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authAuthTokenRefreshCreate>>,
      TError,
      { data: NonReadonly<TokenRefresh> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authAuthTokenRefreshCreate>>,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationOptions = getAuthAuthTokenRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authCoinsAddCreate = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/auth/coins/add`,
    method: "POST",
    signal,
  });
};

export const getAuthCoinsAddCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authCoinsAddCreate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authCoinsAddCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authCoinsAddCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authCoinsAddCreate>>,
    void
  > = () => {
    return authCoinsAddCreate();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthCoinsAddCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authCoinsAddCreate>>
>;

export type AuthCoinsAddCreateMutationError = unknown;

export const useAuthCoinsAddCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authCoinsAddCreate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authCoinsAddCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthCoinsAddCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * POST /api/auth/login/ with {username,password} or {email,password}
Returns: {access, refresh, firstLogin, user}
 */
export const authLoginCreate = (
  courtlyTokenObtainPair: CourtlyTokenObtainPair,
  signal?: AbortSignal,
) => {
  return customRequest<CourtlyTokenObtainPair>({
    url: `/api/auth/login/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: courtlyTokenObtainPair,
    signal,
  });
};

export const getAuthLoginCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLoginCreate>>,
    TError,
    { data: CourtlyTokenObtainPair },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: CourtlyTokenObtainPair },
  TContext
> => {
  const mutationKey = ["authLoginCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLoginCreate>>,
    { data: CourtlyTokenObtainPair }
  > = (props) => {
    const { data } = props ?? {};

    return authLoginCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLoginCreate>>
>;
export type AuthLoginCreateMutationBody = CourtlyTokenObtainPair;
export type AuthLoginCreateMutationError = unknown;

export const useAuthLoginCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLoginCreate>>,
      TError,
      { data: CourtlyTokenObtainPair },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: CourtlyTokenObtainPair },
  TContext
> => {
  const mutationOptions = getAuthLoginCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authMeRetrieve = (signal?: AbortSignal) => {
  return customRequest<void>({ url: `/api/auth/me`, method: "GET", signal });
};

export const getAuthMeRetrieveQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getAuthMeRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthMeRetrieveQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeRetrieve>>> = ({
    signal,
  }) => authMeRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authMeRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthMeRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof authMeRetrieve>>
>;
export type AuthMeRetrieveQueryError = unknown;

export function useAuthMeRetrieve<
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeRetrieve>>,
          TError,
          Awaited<ReturnType<typeof authMeRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthMeRetrieve<
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeRetrieve>>,
          TError,
          Awaited<ReturnType<typeof authMeRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthMeRetrieve<
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAuthMeRetrieve<
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthMeRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const authMePartialUpdate = () => {
  return customRequest<void>({ url: `/api/auth/me`, method: "PATCH" });
};

export const getAuthMePartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authMePartialUpdate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authMePartialUpdate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authMePartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authMePartialUpdate>>,
    void
  > = () => {
    return authMePartialUpdate();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthMePartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authMePartialUpdate>>
>;

export type AuthMePartialUpdateMutationError = unknown;

export const useAuthMePartialUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authMePartialUpdate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authMePartialUpdate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthMePartialUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authMeRetrieve2 = (signal?: AbortSignal) => {
  return customRequest<void>({ url: `/api/auth/me/`, method: "GET", signal });
};

export const getAuthMeRetrieve2QueryKey = () => {
  return [`/api/auth/me/`] as const;
};

export const getAuthMeRetrieve2QueryOptions = <
  TData = Awaited<ReturnType<typeof authMeRetrieve2>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve2>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthMeRetrieve2QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeRetrieve2>>> = ({
    signal,
  }) => authMeRetrieve2(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authMeRetrieve2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthMeRetrieve2QueryResult = NonNullable<
  Awaited<ReturnType<typeof authMeRetrieve2>>
>;
export type AuthMeRetrieve2QueryError = unknown;

export function useAuthMeRetrieve2<
  TData = Awaited<ReturnType<typeof authMeRetrieve2>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authMeRetrieve2>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeRetrieve2>>,
          TError,
          Awaited<ReturnType<typeof authMeRetrieve2>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthMeRetrieve2<
  TData = Awaited<ReturnType<typeof authMeRetrieve2>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authMeRetrieve2>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMeRetrieve2>>,
          TError,
          Awaited<ReturnType<typeof authMeRetrieve2>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthMeRetrieve2<
  TData = Awaited<ReturnType<typeof authMeRetrieve2>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authMeRetrieve2>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAuthMeRetrieve2<
  TData = Awaited<ReturnType<typeof authMeRetrieve2>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authMeRetrieve2>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthMeRetrieve2QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const authMePartialUpdate2 = () => {
  return customRequest<void>({ url: `/api/auth/me/`, method: "PATCH" });
};

export const getAuthMePartialUpdate2MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authMePartialUpdate2>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authMePartialUpdate2>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authMePartialUpdate2"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authMePartialUpdate2>>,
    void
  > = () => {
    return authMePartialUpdate2();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthMePartialUpdate2MutationResult = NonNullable<
  Awaited<ReturnType<typeof authMePartialUpdate2>>
>;

export type AuthMePartialUpdate2MutationError = unknown;

export const useAuthMePartialUpdate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authMePartialUpdate2>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authMePartialUpdate2>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthMePartialUpdate2MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * POST /api/auth/register/
Body accepts: username, email, password, confirm, firstname, lastname, accept
(serializer maps firstname/lastname -> first_name/last_name)
 */
export const authRegisterCreate = (
  register: Register,
  signal?: AbortSignal,
) => {
  return customRequest<Register>({
    url: `/api/auth/register/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: register,
    signal,
  });
};

export const getAuthRegisterCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegisterCreate>>,
    TError,
    { data: Register },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegisterCreate>>,
  TError,
  { data: Register },
  TContext
> => {
  const mutationKey = ["authRegisterCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegisterCreate>>,
    { data: Register }
  > = (props) => {
    const { data } = props ?? {};

    return authRegisterCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRegisterCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRegisterCreate>>
>;
export type AuthRegisterCreateMutationBody = Register;
export type AuthRegisterCreateMutationError = unknown;

export const useAuthRegisterCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegisterCreate>>,
      TError,
      { data: Register },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authRegisterCreate>>,
  TError,
  { data: Register },
  TContext
> => {
  const mutationOptions = getAuthRegisterCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authTokenRefreshCreate = (
  tokenRefresh: NonReadonly<TokenRefresh>,
  signal?: AbortSignal,
) => {
  return customRequest<TokenRefresh>({
    url: `/api/auth/token/refresh/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tokenRefresh,
    signal,
  });
};

export const getAuthTokenRefreshCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authTokenRefreshCreate>>,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authTokenRefreshCreate>>,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationKey = ["authTokenRefreshCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authTokenRefreshCreate>>,
    { data: NonReadonly<TokenRefresh> }
  > = (props) => {
    const { data } = props ?? {};

    return authTokenRefreshCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthTokenRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authTokenRefreshCreate>>
>;
export type AuthTokenRefreshCreateMutationBody = NonReadonly<TokenRefresh>;
export type AuthTokenRefreshCreateMutationError = unknown;

export const useAuthTokenRefreshCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authTokenRefreshCreate>>,
      TError,
      { data: NonReadonly<TokenRefresh> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authTokenRefreshCreate>>,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationOptions = getAuthTokenRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
