/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - pending
 * `confirmed` - confirmed
 * `walkin` - walkin
 * `checkin` - checkin
 * `endgame` - endgame
 * `cancelled` - cancelled
 * `completed` - completed
 * `no_show` - no_show
 */
export type BookingStatusEnum =
  (typeof BookingStatusEnum)[keyof typeof BookingStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStatusEnum = {
  pending: "pending",
  confirmed: "confirmed",
  walkin: "walkin",
  checkin: "checkin",
  endgame: "endgame",
  cancelled: "cancelled",
  completed: "completed",
  no_show: "no_show",
} as const;
