/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { TypeEnum } from "./typeEnum";

/**
 * Transaction history rows for the table in the UI.
 */
export interface CoinLedger {
  readonly id: number;
  type: TypeEnum;
  /**
   * + เข้า (topup/refund), - ออก (capture)
   * @minimum -2147483648
   * @maximum 2147483647
   */
  amount: number;
  /** @nullable */
  ref_booking?: number | null;
  readonly created_at: string;
}
