/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

/**
 * Accepts either {"username","password"} or {"email","password"}.
Makes 'username' optional so posting only email works.
Also updates last_login and returns { firstLogin, user }.
 */
export interface CourtlyTokenObtainPair {
  username?: string;
  password: string;
  email?: string;
}
