/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import type { StatusEnum } from "./statusEnum";

export interface PatchedTopupRequestList {
  readonly id?: number;
  readonly username?: string;
  readonly amount_thb?: number;
  readonly coins?: number;
  /** @nullable */
  readonly transfer_date?: string | null;
  /** @nullable */
  readonly transfer_time?: string | null;
  readonly slip_url?: string;
  readonly status?: StatusEnum;
  readonly created_at?: string;
}
