/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { BookingStatusEnum } from "./bookingStatusEnum";

export interface PatchedBooking {
  readonly id?: number;
  /** @maxLength 24 */
  booking_no?: string;
  club?: number;
  court?: number;
  /** @nullable */
  slot?: number | null;
  status?: BookingStatusEnum;
  readonly created_at?: string;
}
