/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { BookingStatusEnum } from "./bookingStatusEnum";

/**
 * Serializer for Booking.
- Shows readable names (user, club, court) instead of numeric IDs.
- Includes nested slot details under 'slots'.
 */
export interface PatchedBooking {
  /** @maxLength 24 */
  booking_no?: string;
  status?: BookingStatusEnum;
  readonly user?: string;
  readonly club_name?: string;
  readonly court_name?: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  total_cost?: number | null;
  /** @nullable */
  booking_date?: string | null;
  readonly created_at?: string;
  readonly slots?: string;
}
