/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `available` - Available
 * `booked` - Booked
 * `walkin` - Walk-in
 * `checkin` - Check-in
 * `endgame` - Endgame
 * `expired` - Expired
 * `no_show` - No-Show
 * `maintenance` - Maintenance
 */
export type SlotStatusStatusEnum =
  (typeof SlotStatusStatusEnum)[keyof typeof SlotStatusStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SlotStatusStatusEnum = {
  available: "available",
  booked: "booked",
  walkin: "walkin",
  checkin: "checkin",
  endgame: "endgame",
  expired: "expired",
  no_show: "no_show",
  maintenance: "maintenance",
} as const;
