/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `available` - available
 * `booked` - booked
 * `maintenance` - maintenance
 */
export type SlotStatusStatusEnum =
  (typeof SlotStatusStatusEnum)[keyof typeof SlotStatusStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SlotStatusStatusEnum = {
  available: "available",
  booked: "booked",
  maintenance: "maintenance",
} as const;
