/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import type { SlotStatus } from "./slotStatus";

/**
 * Serializer for the Slot model.
- Converts start_at and end_at to local time (HH:MM format).
- Includes the related SlotStatus.
 */
export interface Slot {
  readonly id: number;
  court: number;
  service_date: string;
  readonly start_time: string;
  readonly end_time: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  price_coins?: number;
  readonly slot_status: SlotStatus;
}
