/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { SlotStatusStatusEnum } from "./slotStatusStatusEnum";

/**
 * Serializer for SlotStatus — shows current slot status and last update time.
 */
export interface SlotStatus {
  status?: SlotStatusStatusEnum;
  readonly updated_at: string;
}
