/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { SlotStatus } from "./slotStatus";

export interface Slot {
  readonly id: number;
  court: number;
  service_date: string;
  readonly start_time: string;
  readonly end_time: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  price_coins?: number;
  readonly slot_status: SlotStatus;
}
