/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - Pending
 * `approved` - Approved
 * `rejected` - Rejected
 */
export type StatusE94Enum = (typeof StatusE94Enum)[keyof typeof StatusE94Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusE94Enum = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;
