/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - Pending
 * `approved` - Approved
 * `rejected` - Rejected
 */
export type StatusDe3Enum = (typeof StatusDe3Enum)[keyof typeof StatusDe3Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusDe3Enum = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;
