/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}
