/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}
