/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { StatusDe3Enum } from "./statusDe3Enum";

/**
 * Used when a user submits a top-up via UI.
- Player provides amount_thb, transfer_date, transfer_time, and uploads slip_path (image).
- Backend sets coins 1:1 with THB and status=pending.
 */
export interface TopupRequestCreate {
  readonly id: number;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  amount_thb: number;
  readonly coins: number;
  /** @nullable */
  transfer_date?: string | null;
  /** @nullable */
  transfer_time?: string | null;
  slip_path: string;
  readonly status: StatusDe3Enum;
  readonly created_at: string;
}
