/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import type { StatusDe3Enum } from "./statusDe3Enum";

/**
 * List/retrieve serializer shown to both players and manager.
 */
export interface TopupRequestList {
  readonly id: number;
  readonly username: string;
  readonly amount_thb: number;
  readonly coins: number;
  /** @nullable */
  readonly transfer_date: string | null;
  /** @nullable */
  readonly transfer_time: string | null;
  /** @nullable */
  readonly slip_path: string | null;
  readonly status: StatusDe3Enum;
  readonly created_at: string;
}
