/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import type { StatusE94Enum } from "./statusE94Enum";

export interface TopupRequestCreate {
  readonly id: number;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  amount_thb: number;
  readonly coins: number;
  /** @nullable */
  transfer_date?: string | null;
  /** @nullable */
  transfer_time?: string | null;
  slip_path: string;
  readonly slip_url: string;
  readonly status: StatusE94Enum;
  readonly created_at: string;
}
