/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `topup` - topup
 * `capture` - capture
 * `refund` - refund
 */
export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeEnum = {
  topup: "topup",
  capture: "capture",
  refund: "refund",
} as const;
