/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customRequest } from "../../custom-client";

/**
 * Public calendar: GET /available-slots/?club=<id>&month=YYYY-MM
Response fields must match doc: available_percent (0-1), available_slots[], date: DD-MM-YY
 */
export const availableSlotsRetrieve = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/available-slots/`,
    method: "GET",
    signal,
  });
};

export const getAvailableSlotsRetrieveQueryKey = () => {
  return [`/api/available-slots/`] as const;
};

export const getAvailableSlotsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof availableSlotsRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof availableSlotsRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAvailableSlotsRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof availableSlotsRetrieve>>
  > = ({ signal }) => availableSlotsRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof availableSlotsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AvailableSlotsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof availableSlotsRetrieve>>
>;
export type AvailableSlotsRetrieveQueryError = unknown;

export function useAvailableSlotsRetrieve<
  TData = Awaited<ReturnType<typeof availableSlotsRetrieve>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof availableSlotsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof availableSlotsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof availableSlotsRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAvailableSlotsRetrieve<
  TData = Awaited<ReturnType<typeof availableSlotsRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof availableSlotsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof availableSlotsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof availableSlotsRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAvailableSlotsRetrieve<
  TData = Awaited<ReturnType<typeof availableSlotsRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof availableSlotsRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAvailableSlotsRetrieve<
  TData = Awaited<ReturnType<typeof availableSlotsRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof availableSlotsRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAvailableSlotsRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
