/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customRequest } from "../../custom-client";

/**
 * Players — Get bookings belonging to the current user.
 */
export const myBookingsRetrieve = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/my-bookings/`,
    method: "GET",
    signal,
  });
};

export const getMyBookingsRetrieveQueryKey = () => {
  return [`/api/my-bookings/`] as const;
};

export const getMyBookingsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof myBookingsRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof myBookingsRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMyBookingsRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof myBookingsRetrieve>>
  > = ({ signal }) => myBookingsRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof myBookingsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MyBookingsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof myBookingsRetrieve>>
>;
export type MyBookingsRetrieveQueryError = unknown;

export function useMyBookingsRetrieve<
  TData = Awaited<ReturnType<typeof myBookingsRetrieve>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof myBookingsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof myBookingsRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMyBookingsRetrieve<
  TData = Awaited<ReturnType<typeof myBookingsRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof myBookingsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof myBookingsRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMyBookingsRetrieve<
  TData = Awaited<ReturnType<typeof myBookingsRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingsRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMyBookingsRetrieve<
  TData = Awaited<ReturnType<typeof myBookingsRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof myBookingsRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMyBookingsRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
