# Generated by Django 5.2.6 on 2025-09-16 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('checked_in', 'checked_in'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('no_show', 'no_show')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.club')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.court')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('dow', models.PositiveSmallIntegerField(default=0)),
                ('price_coins', models.PositiveIntegerField(default=50)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.court')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='booking.booking')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='booking.slot')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.slot'),
        ),
        migrations.CreateModel(
            name='SlotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('maintenance', 'maintenance')], default='available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_status', to='booking.slot')),
            ],
            options={
                'verbose_name': 'Slot Status',
                'verbose_name_plural': 'Slot Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['court', 'service_date'], name='booking_slo_court_i_8d3d6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('court', 'start_at')},
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['booking'], name='booking_boo_booking_dfce9f_idx'),
        ),
    ]
