# Generated by Django 5.2.5 on 2025-09-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('maintenance', 'maintenance')], default='available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slot Status',
                'verbose_name_plural': 'Slot Statuses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slot',
            name='dow',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='price_coins',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['booking'], name='booking_boo_booking_dfce9f_idx'),
        ),
        migrations.AddField(
            model_name='slotstatus',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_status', to='booking.slot'),
        ),
    ]
