# Generated by Django 5.2.7 on 2025-10-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_slotstatus_alter_bookingslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('walkin', 'walkin'), ('checkin', 'checkin'), ('endgame', 'endgame'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('no_show', 'no_show')], default='confirmed', max_length=20),
        ),
    ]
