# Generated by Django 5.2.6 on 2025-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_slotstatus_alter_bookingslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotstatus',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('walkin', 'walkin'), ('checkin', 'checkin'), ('endgame', 'endgame'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('no_show', 'no_show')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='slotstatus',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('walkin', 'Walk-in'), ('checkin', 'Check-in'), ('endgame', 'Endgame'), ('expired', 'Expired'), ('no_show', 'No-Show'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
