# Generated by Django 5.2.7 on 2025-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_booking_date_booking_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotstatus',
            options={},
        ),
        migrations.AlterField(
            model_name='slotstatus',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('walkin', 'Walk-in'), ('checkin', 'Check-in'), ('endgame', 'Endgame'), ('expired', 'Expired'), ('no_show', 'No-Show'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
