# Generated by Django 5.2.7 on 2025-10-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_slotstatus_options_booking_booking_date_and_more'),
        ('booking', '0004_alter_slotstatus_options_alter_slotstatus_status'),
    ]

    operations = [
    ]
