# Generated by Django 5.2.7 on 2025-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_contact_detail_booking_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
