# Generated by Django 5.2.8 on 2025-11-17 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_booking_method_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='booking.slot'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('booking', 'slot')},
        ),
    ]
