name: Build, Push, and Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-frontend-prod:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-frontend-prod:${{ github.sha }}

      # 4. Deploy to DigitalOcean App Platform
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app_name: courtly-project-frontend-prod
