name: Build, Push and Deploy Frontend

on:
  push:
    branches:
      - main
      - feat/setup-cicd   # dev branch

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Set image repo based on branch
      - name: Set image repo
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "repo=${{ github.repository }}-frontend-prod" >> $GITHUB_OUTPUT
          else
            echo "repo=${{ github.repository }}-frontend-dev" >> $GITHUB_OUTPUT
          fi

      # 4. Build and push Docker image
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.repo }}:latest

      # 5. Deploy to DigitalOcean
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        env:
          IMAGE_DIGEST: ${{ steps.push.outputs.digest }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
