/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Courtly API
 * Badminton Court Management & Booking System
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { Slot } from "../../schemas";

import { customRequest } from "../../custom-client";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const slotsList = (signal?: AbortSignal) => {
  return customRequest<Slot[]>({ url: `/api/slots/`, method: "GET", signal });
};

export const getSlotsListQueryKey = () => {
  return [`/api/slots/`] as const;
};

export const getSlotsListQueryOptions = <
  TData = Awaited<ReturnType<typeof slotsList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSlotsListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof slotsList>>> = ({
    signal,
  }) => slotsList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof slotsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SlotsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof slotsList>>
>;
export type SlotsListQueryError = unknown;

export function useSlotsList<
  TData = Awaited<ReturnType<typeof slotsList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof slotsList>>,
          TError,
          Awaited<ReturnType<typeof slotsList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSlotsList<
  TData = Awaited<ReturnType<typeof slotsList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof slotsList>>,
          TError,
          Awaited<ReturnType<typeof slotsList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSlotsList<
  TData = Awaited<ReturnType<typeof slotsList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSlotsList<
  TData = Awaited<ReturnType<typeof slotsList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSlotsListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const slotsRetrieve = (id: number, signal?: AbortSignal) => {
  return customRequest<Slot>({
    url: `/api/slots/${id}/`,
    method: "GET",
    signal,
  });
};

export const getSlotsRetrieveQueryKey = (id?: number) => {
  return [`/api/slots/${id}/`] as const;
};

export const getSlotsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof slotsRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsRetrieve>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSlotsRetrieveQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof slotsRetrieve>>> = ({
    signal,
  }) => slotsRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof slotsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SlotsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof slotsRetrieve>>
>;
export type SlotsRetrieveQueryError = unknown;

export function useSlotsRetrieve<
  TData = Awaited<ReturnType<typeof slotsRetrieve>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsRetrieve>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof slotsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof slotsRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSlotsRetrieve<
  TData = Awaited<ReturnType<typeof slotsRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsRetrieve>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof slotsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof slotsRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSlotsRetrieve<
  TData = Awaited<ReturnType<typeof slotsRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsRetrieve>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSlotsRetrieve<
  TData = Awaited<ReturnType<typeof slotsRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof slotsRetrieve>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSlotsRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * GET /api/month-view/?club=1&month=2025-11
 */
export const slotsMonthViewRetrieve = (signal?: AbortSignal) => {
  return customRequest<Slot>({
    url: `/api/slots/month-view/`,
    method: "GET",
    signal,
  });
};

export const getSlotsMonthViewRetrieveQueryKey = () => {
  return [`/api/slots/month-view/`] as const;
};

export const getSlotsMonthViewRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSlotsMonthViewRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof slotsMonthViewRetrieve>>
  > = ({ signal }) => slotsMonthViewRetrieve(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SlotsMonthViewRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof slotsMonthViewRetrieve>>
>;
export type SlotsMonthViewRetrieveQueryError = unknown;

export function useSlotsMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
          TError,
          Awaited<ReturnType<typeof slotsMonthViewRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSlotsMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
          TError,
          Awaited<ReturnType<typeof slotsMonthViewRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSlotsMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSlotsMonthViewRetrieve<
  TData = Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof slotsMonthViewRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSlotsMonthViewRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * POST /api/slots/slots-list/
Body: {
    "slot_list": ["25188", "25189"]
}
 */
export const slotsSlotsListCreate = (
  slot: NonReadonly<Slot>,
  signal?: AbortSignal,
) => {
  return customRequest<Slot>({
    url: `/api/slots/slots-list/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: slot,
    signal,
  });
};

export const getSlotsSlotsListCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof slotsSlotsListCreate>>,
    TError,
    { data: NonReadonly<Slot> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof slotsSlotsListCreate>>,
  TError,
  { data: NonReadonly<Slot> },
  TContext
> => {
  const mutationKey = ["slotsSlotsListCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof slotsSlotsListCreate>>,
    { data: NonReadonly<Slot> }
  > = (props) => {
    const { data } = props ?? {};

    return slotsSlotsListCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SlotsSlotsListCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof slotsSlotsListCreate>>
>;
export type SlotsSlotsListCreateMutationBody = NonReadonly<Slot>;
export type SlotsSlotsListCreateMutationError = unknown;

export const useSlotsSlotsListCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof slotsSlotsListCreate>>,
      TError,
      { data: NonReadonly<Slot> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof slotsSlotsListCreate>>,
  TError,
  { data: NonReadonly<Slot> },
  TContext
> => {
  const mutationOptions = getSlotsSlotsListCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Simple bulk slot status update.
 */
export const slotsStatusCreate = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/slots/status/`,
    method: "POST",
    signal,
  });
};

export const getSlotsStatusCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof slotsStatusCreate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof slotsStatusCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["slotsStatusCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof slotsStatusCreate>>,
    void
  > = () => {
    return slotsStatusCreate();
  };

  return { mutationFn, ...mutationOptions };
};

export type SlotsStatusCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof slotsStatusCreate>>
>;

export type SlotsStatusCreateMutationError = unknown;

export const useSlotsStatusCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof slotsStatusCreate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof slotsStatusCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSlotsStatusCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const slotsUpdateStatusCreate = (signal?: AbortSignal) => {
  return customRequest<void>({
    url: `/api/slots/update-status/`,
    method: "POST",
    signal,
  });
};

export const getSlotsUpdateStatusCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof slotsUpdateStatusCreate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof slotsUpdateStatusCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["slotsUpdateStatusCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof slotsUpdateStatusCreate>>,
    void
  > = () => {
    return slotsUpdateStatusCreate();
  };

  return { mutationFn, ...mutationOptions };
};

export type SlotsUpdateStatusCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof slotsUpdateStatusCreate>>
>;

export type SlotsUpdateStatusCreateMutationError = unknown;

export const useSlotsUpdateStatusCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof slotsUpdateStatusCreate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof slotsUpdateStatusCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSlotsUpdateStatusCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
